const tours = [
  {
    title: "The Sea Explorer",
    difficulty: "Medium",
    days: 7,
    description: "Exploring the jaw-dropping US east coast by foot and by boat",
    location: "Miami, USA",
    date: "Dec 2021",
    stops: 4,
    possiblePeople: 15,
  },
  {
    title: "The Forest Hiker",
    difficulty: "Esay",
    days: 5,
    description: "Breathtaking hike through the Canadian Banff National Park",
    location: "Baff, CAN",
    date: "Jan 2022",
    stops: 3,
    possiblePeople: 25,
  },
  {
    title: "The Park Camper",
    difficulty: "Medium",
    days: 10,
    description:
      "Breathing in Nature in America's most spectacular National Parks",
    location: "Las Vegas, USA",
    date: "Feb 2022",
    stops: 4,
    possiblePeople: 15,
  },
  {
    title: "The Forest Hiker",
    difficulty: "Esay",
    days: 5,
    description: "Breathtaking hike through the Canadian Banff National Park",
    location: "Baff, CAN",
    date: "Jan 2022",
    stops: 3,
    possiblePeople: 25,
  },
  {
    title: "The City Wanderer",
    difficulty: "esay",
    days: 9,
    description:
      "Living the life of Wanderlust in the US' most beatiful cities",
    location: "NYC, USA",
    date: "Mar 2022",
    stops: 3,
    possiblePeople: 20,
  },
  ,
  {
    title: "The Northenrn lights",
    difficulty: "esay",
    days: 3,
    description:
      "Enjoy the Northern Lights in one of the best places in the world",
    location: "YellowKnife, CAN",
    date: "May 2022",
    stops: 1,
    possiblePeople: 12,
  },
  {
    title: "The Dalat City",
    difficulty: "esay",
    days: 10,
    description: "Living the life of the most beautiful city of LD",
    location: "Dalat, VN",
    date: "Apr 2022",
    stops: 5,
    possiblePeople: 30,
  },
];
